### ISSUE TITLE
TypeScript 3.6 Compatibility issue

### ISSUE THREAD

**Issue by septs** [xdave/typescript-fsa-redux-thunk#17]
```
      TS2345: Argument of type '{ (payload: Success<string, void>, meta?: { [key: string]: any; } | null | undefined): Action<Success<string, void>>; type: string; match: (action: AnyAction) => action is Action<Success<string, void>>; }' is not assignable to parameter of type '{ (payload: { params: string; } & { result: void; }, meta?: { [key: string]: any; } | null | undefined): Action<{ params: string; } & { result: void; }>; type: string; match: (action: AnyAction) => action is Action<{ ...; } & { ...; }>; }'.
  Types of property 'match' are incompatible.
    Type '(action: AnyAction) => action is Action<Success<string, void>>' is not assignable to type '(action: AnyAction) => action is Action<{ params: string; } & { result: void; }>'.
      Type predicate 'action is Action<Success<string, void>>' is not assignable to 'action is Action<{ params: string; } & { result: void; }>'.
        Type 'Action<Success<string, void>>' is not assignable to type 'Action<{ params: string; } & { result: void; }>'.
          Type 'Success<string, void>' is not assignable to type '{ params: string; } & { result: void; }'.
            Type '{ params: string; } & { result?: void | undefined; }' is not assignable to type '{ params: string; } & { result: void; }'.
              Type '{ params: string; } & { result?: void | undefined; }' is not assignable to type '{ result: void; }'.
                Property 'result' is optional in type '{ params: string; } & { result?: void | undefined; }' but required in type '{ result: void; }'.
```

Key line
```
Type predicate 'action is Action<Success<string, void>>' is not assignable to 'action is Action<{ params: string; } & { result: void; }>'
```

**Comment by xdave** [comment]
@septs Can you give me some example code that demonstrates this? Thanks.

**Comment by septs** [comment]
Minimum PoC:
https://gist.github.com/septs/7e27d0f7dbbe00675ef4cf10f61dba8d

**Comment by septs** [comment]
**typescript-fsa** issue?

https://github.com/aikoven/typescript-fsa/blob/7a30492309f9ef63e9bc6a954787d0c0032f162b/src/index.ts#L84-L86

**Comment by xdave** [comment]
I can confirm that this isn't directly an issue with `typescript-fsa-redux-thunk`.  The type of `Success` in `typescript-fsa` seem to be causing the problem.  It's specifically checking if the return type is `void` to make the `result` part of `Success` optional, which is conflicting with the return type of the thunk

The thunk wants to return `void` without it being also possibly an undefined void, but `typescript-fsa` wants to see it as `void | undefined`.

Forcing `createAsync` to use `void | undefined` doesn't work, because `void` is being narrowed conditionally by `typescript-fsa` and turns it into `undefined`, which is not technically a valid return type.

A work around would be to force the async factory function to have a return type of `unknown`:

```ts
const example = createAsync<unknown, unknown>('example', Promise.resolve);
```

or specify it as an empty interface/type object:

```ts
const example = createAsync<unknown, {}>('example', Promise.resolve);
```

I'm going to keep looking if there's a way I can work around this in this project.

**Comment by xdave** [comment]
I think I figured this out.  I've created a workaround in my code that avoids using the `void` type to determine the `result`, but rather forces it to be inferred through `unknown`.

As far as I can tell, the workaround doesn't break anything else.

Please check this out in https://github.com/xdave/typescript-fsa-redux-thunk/tree/issue-17

**Comment by xdave** [comment]
@septs check it out: 2.1.5 released to npm.

**Comment by septs** [comment]
@xdave `index.spec.ts` may need void return use case.

**Comment by xdave** [comment]
I have created `issue-17.spec.ts` that covers all of this.

**Comment by xdave** [comment]
I've added some tests to `index.spec.ts` and upgraded the typescript-fsa dependency to 3.0.0 stable (instead of beta), and I'm preparing 2.1.6 right now.

**Comment by xdave** [comment]
@septs https://www.npmjs.com/package/typescript-fsa-redux-thunk/v/2.1.6
